/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.toolsmanager2.mainapp;

import com.mycompany.toolsmanager2.dataaccess.DataAccess;
import com.mycompany.toolsmanager2.models.Usuari;
import com.mycompany.toolsmanager2.panels.DeleteUser;
import com.mycompany.toolsmanager2.panels.InventariCount;
import com.mycompany.toolsmanager2.panels.ListUsersPanel;
import com.mycompany.toolsmanager2.panels.UserInfo;
import com.mycompany.toolsmanager2.startapp.Login;
import static com.mycompany.toolsmanager2.utils.Utils.resizeImageIcon1;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.WindowConstants;

/**
 *
 * @author Diego Ramirez
 */
public class MainFrame extends javax.swing.JFrame {
    //ListUsersPanel pnlUsersList;
    //UserInfo userInfo;
    public static  boolean logged = false;
    public static  int idUsuari;
    
  
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUser = new javax.swing.JMenu();
        mniProfile = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        mniDeleteUser = new javax.swing.JMenuItem();
        mnuStats = new javax.swing.JMenu();
        mniListUsers = new javax.swing.JMenuItem();
        mniInventariCount = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mnuUser.setText("Login");

        mniProfile.setText("My Profile");
        mniProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProfileActionPerformed(evt);
            }
        });
        mnuUser.add(mniProfile);

        mniLogout.setText("Logout");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuUser.add(mniLogout);

        mniDeleteUser.setText("DeleteUser");
        mniDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeleteUserActionPerformed(evt);
            }
        });
        mnuUser.add(mniDeleteUser);

        jMenuBar1.add(mnuUser);

        mnuStats.setText("Actions");

        mniListUsers.setText("List Users");
        mniListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListUsersActionPerformed(evt);
            }
        });
        mnuStats.add(mniListUsers);

        mniInventariCount.setText("InventariCount");
        mniInventariCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInventariCountActionPerformed(evt);
            }
        });
        mnuStats.add(mniInventariCount);

        jMenuBar1.add(mnuStats);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProfileActionPerformed
        // TODO add your handling code here:
         hideActivePanel();
         if(logged = true){
        UserInfo pnlUsersI = new UserInfo();
        getContentPane().add(pnlUsersI, java.awt.BorderLayout.CENTER);}
        pack();
    }//GEN-LAST:event_mniProfileActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login(this, true);
        login.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        hideActivePanel();
        login.setVisible(true);
        MainFrame.logged = false;
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListUsersActionPerformed
        // TODO add your handling code here:
        hideActivePanel();
        /*if(pnlUsersList == null){
        ListUsersPanel pnlUsersList = new ListUsersPanel();
        getContentPane().add(pnlUsersList, java.awt.BorderLayout.CENTER);
        pack();
        }else{
        pnlUsersList.setVisible(true);
        }*/
        ListUsersPanel pnlUsersList = new ListUsersPanel();
        getContentPane().add(pnlUsersList, java.awt.BorderLayout.CENTER);
        pack();
  
    }//GEN-LAST:event_mniListUsersActionPerformed

    private void mniInventariCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInventariCountActionPerformed
        // TODO add your handling code here:
        hideActivePanel();
        InventariCount pnlIC = new InventariCount();
        getContentPane().add(pnlIC, java.awt.BorderLayout.CENTER);
        pack();
        
    }//GEN-LAST:event_mniInventariCountActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Login login = new Login(this, true);
        login.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        login.setVisible(true);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void mniDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeleteUserActionPerformed
        // TODO add your handling code here:
        hideActivePanel();
        DeleteUser deleteUser = new DeleteUser();
        getContentPane().add(deleteUser, java.awt.BorderLayout.CENTER);
        pack();
    }//GEN-LAST:event_mniDeleteUserActionPerformed

    private void hideActivePanel(){
        Component[] panels = getContentPane().getComponents();
        for (Component c: panels) {
            if(c.isVisible()){
                c.setVisible(false);
                /*getContentPane().remove(c); //Para que no se guarden los datos y cada vez que volvamos los datos esten en blanco
                c = null;*/
            }
        }
    }
    
    /*public void showUserInfo(){
        if(logged = true){
            lblUserName.setText(username);
            BufferedImage originalImage = null;
            try {
                originalImage = ImageIO.read(new File(photo));
                ImageIcon icon = Utils.resizeImageIcon(originalImage, lblUserImage.getWidth(), lblUserImage.getHeight());
                lblUserImage.setIcon(icon);
            } catch (IOException ioe) {
                System.out.println("Imagen no valida");
            }catch(NullPointerException e) {
             System.out.println("NullPointerException thrown!");
            }
        }
        
    }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniDeleteUser;
    private javax.swing.JMenuItem mniInventariCount;
    private javax.swing.JMenuItem mniListUsers;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniProfile;
    private javax.swing.JMenu mnuStats;
    private javax.swing.JMenu mnuUser;
    // End of variables declaration//GEN-END:variables
}
