/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.toolsmanager2.panels;

import com.mycompany.toolsmanager2.dataaccess.DataAccess;
import com.mycompany.toolsmanager2.mainapp.MainFrame;
import com.mycompany.toolsmanager2.models.Intents;
import com.mycompany.toolsmanager2.models.Usuari;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Diego Ramirez
 */
public class DeleteUser extends javax.swing.JPanel {
    DataAccess da = new DataAccess();
    JList<Usuari> lstUsuaris;
    ArrayList<Usuari> users;

    /**
     * Creates new form BestTime
     */
    public DeleteUser() {
        initComponents();
        lstUsuaris = new JList();
        srcUsers.setViewportView(lstUsuaris);
        users = da.getUsers();
        DefaultListModel<Usuari> userListModel = new DefaultListModel<>();
        for (Usuari u: users)
        {
            u.setNom(u.getNom());
            u.setLlinatge(u.getLlinatge());
            userListModel.addElement(u);
        }
        lstUsuaris.setModel(userListModel);
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener(){
	public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            try {
                lstUsersValueChanged(evt);
            } catch (SQLException ex) {
                Logger.getLogger(DeleteUser.class.getName()).log(Level.SEVERE, null, ex);
            }
	}
});
    }
    
       private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) throws SQLException {
       MainFrame m = new MainFrame();
       Usuari selectedUser = lstUsuaris.getSelectedValue();
       if(selectedUser.getId() != m.idUsuari){
       da.deleteUser(selectedUser);
       System.out.println("User succesfully deleted");
       }else{
               System.out.println("Cant delete current user");
               }
 
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srcUsers = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Click on an User to Delete it");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(srcUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(srcUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane srcUsers;
    // End of variables declaration//GEN-END:variables
}
