/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.toolsmanager2.panels;

import com.mycompany.toolsmanager2.dataaccess.DataAccess;
import com.mycompany.toolsmanager2.models.Eina;
import com.mycompany.toolsmanager2.models.Usuari;
import com.mycompany.toolsmanager2.utils.Utils;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author Diego Ramirez
 */
public class InventariCount extends javax.swing.JPanel {
    DataAccess da = new DataAccess();
    JList<Usuari> lstUsuaris;
    ArrayList<Usuari> users;

    /**
     * Creates new form InventariCount
     */
    public InventariCount() {
        initComponents();
        lstUsuaris = new JList();
        srcUsers.setViewportView(lstUsuaris);
        users = da.getUsers();
        DefaultListModel<Usuari> userListModel = new DefaultListModel<>();
        for (Usuari u: users)
        {
            u.setNom(u.getNom());
            u.setLlinatge(u.getLlinatge());
            userListModel.addElement(u);
        }
        lstUsuaris.setModel(userListModel);
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener(){
	public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
		lstUsersValueChanged(evt);
	}
});
    }
    
       private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {
       Usuari selectedUser = lstUsuaris.getSelectedValue();
       int total = da.getCommentCount(selectedUser);
       lblTotalTools.setText(String.valueOf(total));
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srcUsers = new javax.swing.JScrollPane();
        lblTotalTools = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblTotalTools.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalTools.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalTools.setText("                 ");
        lblTotalTools.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Total Tools");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(srcUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblTotalTools)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(srcUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalTools, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTotalTools;
    private javax.swing.JScrollPane srcUsers;
    // End of variables declaration//GEN-END:variables
}
