/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.toolsmanager2.panels;

import com.mycompany.toolsmanager2.dataaccess.DataAccess;
import com.mycompany.toolsmanager2.models.Eina;
import com.mycompany.toolsmanager2.models.Usuari;
import com.mycompany.toolsmanager2.utils.Utils;
import static com.mycompany.toolsmanager2.utils.Utils.resizeImageIcon1;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author Diego Ramirez
 */
public class ListUsersPanel extends javax.swing.JPanel {
   DataAccess da = new DataAccess();
    JList<Usuari> lstUsuaris;
    ArrayList<Usuari> users;
    
    /**
     * Creates new form ListUsersPanel
     */
    public ListUsersPanel() {
        initComponents();
         lstUsuaris = new JList();
        jspUsers.setViewportView(lstUsuaris);
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener(){
	public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
		lstUsersValueChanged(evt);
	}
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListUsers = new javax.swing.JButton();
        jspUsers = new javax.swing.JScrollPane();
        lblUsuari = new javax.swing.JLabel();
        pnlEines = new javax.swing.JPanel();

        btnListUsers.setText("List");
        btnListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListUsersActionPerformed(evt);
            }
        });

        lblUsuari.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnListUsers)
                        .addContainerGap(394, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlEines, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jspUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnListUsers)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlEines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListUsersActionPerformed
        // TODO add your handling code here:
        users = da.getUsers();
        DefaultListModel<Usuari> userListModel = new DefaultListModel<>();
        for (Usuari u: users)
        {
            userListModel.addElement(u);
        }
        lstUsuaris.setModel(userListModel);
    }//GEN-LAST:event_btnListUsersActionPerformed

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {
       pnlEines.removeAll();
       repaint();
       Usuari selectedUser = lstUsuaris.getSelectedValue();
       ArrayList<Eina> eines = da.getTools(selectedUser.getId());
       for(Eina e: eines){
           ImatgePanel imatgePanel = new ImatgePanel();
           imatgePanel.setNomEina(e.getNom());
           imatgePanel.setImagePath(e.getFoto());
           pnlEines.add(imatgePanel);
       }
       
          try {
                File f = new File(selectedUser.getFoto());
                BufferedImage profileBufferedImage = ImageIO.read(f);
                ImageIcon icon  = Utils.resizeImageIcon1(profileBufferedImage, lblUsuari.getWidth(), lblUsuari.getHeight());;
                lblUsuari.setIcon(icon);
            }
            catch(IOException ioe) {
                System.out.println("Image not in pc data");
            }
       
       
       
       
      ((JFrame)(this.getRootPane().getParent())).pack();
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListUsers;
    private javax.swing.JScrollPane jspUsers;
    private javax.swing.JLabel lblUsuari;
    private javax.swing.JPanel pnlEines;
    // End of variables declaration//GEN-END:variables
}
